# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'journal_design.ui'
#
# Created: Wed Oct  5 13:46:07 2016
#      by: PyQt4 UI code generator 4.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1290, 710)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout_2 = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.groupBox = QtGui.QGroupBox(self.centralwidget)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.formLayout = QtGui.QFormLayout(self.groupBox)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.instrumentLabel = QtGui.QLabel(self.groupBox)
        self.instrumentLabel.setObjectName(_fromUtf8("instrumentLabel"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.instrumentLabel)
        self.instrumentComboBox = QtGui.QComboBox(self.groupBox)
        self.instrumentComboBox.setObjectName(_fromUtf8("instrumentComboBox"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.instrumentComboBox)
        self.gridLayout_2.addWidget(self.groupBox, 0, 0, 1, 1)
        self.groupBox_2 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.gridLayout = QtGui.QGridLayout(self.groupBox_2)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.iptsLineEdit = QtGui.QLineEdit(self.groupBox_2)
        self.iptsLineEdit.setObjectName(_fromUtf8("iptsLineEdit"))
        self.gridLayout.addWidget(self.iptsLineEdit, 3, 6, 1, 1)
        self.line_3 = QtGui.QFrame(self.groupBox_2)
        self.line_3.setFrameShape(QtGui.QFrame.VLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName(_fromUtf8("line_3"))
        self.gridLayout.addWidget(self.line_3, 0, 0, 4, 1)
        self.titleLabel = QtGui.QLabel(self.groupBox_2)
        self.titleLabel.setObjectName(_fromUtf8("titleLabel"))
        self.gridLayout.addWidget(self.titleLabel, 0, 1, 1, 1)
        self.titleLineEdit = QtGui.QLineEdit(self.groupBox_2)
        self.titleLineEdit.setObjectName(_fromUtf8("titleLineEdit"))
        self.gridLayout.addWidget(self.titleLineEdit, 0, 2, 1, 1)
        self.line = QtGui.QFrame(self.groupBox_2)
        self.line.setFrameShape(QtGui.QFrame.VLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.gridLayout.addWidget(self.line, 0, 4, 4, 1)
        self.userLabel = QtGui.QLabel(self.groupBox_2)
        self.userLabel.setObjectName(_fromUtf8("userLabel"))
        self.gridLayout.addWidget(self.userLabel, 0, 5, 1, 1)
        self.userLineEdit = QtGui.QLineEdit(self.groupBox_2)
        self.userLineEdit.setObjectName(_fromUtf8("userLineEdit"))
        self.gridLayout.addWidget(self.userLineEdit, 0, 6, 1, 1)
        self.line_2 = QtGui.QFrame(self.groupBox_2)
        self.line_2.setFrameShape(QtGui.QFrame.VLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.gridLayout.addWidget(self.line_2, 0, 7, 4, 1)
        self.dateComboBox = QtGui.QComboBox(self.groupBox_2)
        self.dateComboBox.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.dateComboBox.setObjectName(_fromUtf8("dateComboBox"))
        self.gridLayout.addWidget(self.dateComboBox, 0, 8, 1, 1)
        self.dateTimeEdit = QtGui.QDateTimeEdit(self.groupBox_2)
        self.dateTimeEdit.setObjectName(_fromUtf8("dateTimeEdit"))
        self.gridLayout.addWidget(self.dateTimeEdit, 0, 9, 1, 1)
        self.dateToLabel = QtGui.QLabel(self.groupBox_2)
        self.dateToLabel.setTextFormat(QtCore.Qt.LogText)
        self.dateToLabel.setObjectName(_fromUtf8("dateToLabel"))
        self.gridLayout.addWidget(self.dateToLabel, 0, 10, 1, 1)
        self.dateTimeEdit_2 = QtGui.QDateTimeEdit(self.groupBox_2)
        self.dateTimeEdit_2.setObjectName(_fromUtf8("dateTimeEdit_2"))
        self.gridLayout.addWidget(self.dateTimeEdit_2, 0, 11, 1, 1)
        self.titleCaseCheckBox = QtGui.QCheckBox(self.groupBox_2)
        self.titleCaseCheckBox.setObjectName(_fromUtf8("titleCaseCheckBox"))
        self.gridLayout.addWidget(self.titleCaseCheckBox, 3, 2, 1, 1)
        self.iptsLabel = QtGui.QLabel(self.groupBox_2)
        self.iptsLabel.setObjectName(_fromUtf8("iptsLabel"))
        self.gridLayout.addWidget(self.iptsLabel, 3, 5, 1, 1)
        self.scanLabel = QtGui.QLabel(self.groupBox_2)
        self.scanLabel.setObjectName(_fromUtf8("scanLabel"))
        self.gridLayout.addWidget(self.scanLabel, 3, 8, 1, 1)
        self.scanStartSpinBox = QtGui.QSpinBox(self.groupBox_2)
        self.scanStartSpinBox.setMinimum(1)
        self.scanStartSpinBox.setMaximum(99999)
        self.scanStartSpinBox.setObjectName(_fromUtf8("scanStartSpinBox"))
        self.gridLayout.addWidget(self.scanStartSpinBox, 3, 9, 1, 1)
        self.scanToLabel = QtGui.QLabel(self.groupBox_2)
        self.scanToLabel.setTextFormat(QtCore.Qt.LogText)
        self.scanToLabel.setObjectName(_fromUtf8("scanToLabel"))
        self.gridLayout.addWidget(self.scanToLabel, 3, 10, 1, 1)
        self.scanStopSpinBox = QtGui.QSpinBox(self.groupBox_2)
        self.scanStopSpinBox.setMinimum(1)
        self.scanStopSpinBox.setMaximum(99999)
        self.scanStopSpinBox.setObjectName(_fromUtf8("scanStopSpinBox"))
        self.gridLayout.addWidget(self.scanStopSpinBox, 3, 11, 1, 1)
        self.titleSyntaxComboBox = QtGui.QComboBox(self.groupBox_2)
        self.titleSyntaxComboBox.setObjectName(_fromUtf8("titleSyntaxComboBox"))
        self.gridLayout.addWidget(self.titleSyntaxComboBox, 0, 3, 1, 1)
        self.gridLayout_2.addWidget(self.groupBox_2, 0, 1, 1, 1)
        self.tableView = QtGui.QTableView(self.centralwidget)
        self.tableView.setObjectName(_fromUtf8("tableView"))
        self.gridLayout_2.addWidget(self.tableView, 1, 0, 1, 2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1290, 20))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menu_File = QtGui.QMenu(self.menubar)
        self.menu_File.setObjectName(_fromUtf8("menu_File"))
        self.menuImport = QtGui.QMenu(self.menu_File)
        self.menuImport.setObjectName(_fromUtf8("menuImport"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.actionHDF5 = QtGui.QAction(MainWindow)
        self.actionHDF5.setObjectName(_fromUtf8("actionHDF5"))
        self.actionCSV = QtGui.QAction(MainWindow)
        self.actionCSV.setObjectName(_fromUtf8("actionCSV"))
        self.actionXML = QtGui.QAction(MainWindow)
        self.actionXML.setObjectName(_fromUtf8("actionXML"))
        self.action_Plot = QtGui.QAction(MainWindow)
        self.action_Plot.setObjectName(_fromUtf8("action_Plot"))
        self.action_Close = QtGui.QAction(MainWindow)
        self.action_Close.setObjectName(_fromUtf8("action_Close"))
        self.menuImport.addAction(self.actionHDF5)
        self.menuImport.addAction(self.actionCSV)
        self.menuImport.addAction(self.actionXML)
        self.menu_File.addAction(self.menuImport.menuAction())
        self.menu_File.addAction(self.action_Plot)
        self.menu_File.addSeparator()
        self.menu_File.addAction(self.action_Close)
        self.menubar.addAction(self.menu_File.menuAction())
        self.instrumentLabel.setBuddy(self.instrumentComboBox)
        self.titleLabel.setBuddy(self.titleLineEdit)
        self.userLabel.setBuddy(self.userLineEdit)
        self.iptsLabel.setBuddy(self.iptsLineEdit)
        self.scanLabel.setBuddy(self.scanStartSpinBox)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "JournalView", None))
        self.groupBox.setTitle(_translate("MainWindow", "Display", None))
        self.instrumentLabel.setText(_translate("MainWindow", "Instrument:", None))
        self.groupBox_2.setTitle(_translate("MainWindow", "Filter", None))
        self.titleLabel.setText(_translate("MainWindow", "Title:", None))
        self.userLabel.setText(_translate("MainWindow", "User:", None))
        self.dateToLabel.setText(_translate("MainWindow", "to", None))
        self.titleCaseCheckBox.setText(_translate("MainWindow", "Case Sensitive", None))
        self.iptsLabel.setText(_translate("MainWindow", "IPTS:", None))
        self.scanLabel.setText(_translate("MainWindow", "Scan ID:", None))
        self.scanToLabel.setText(_translate("MainWindow", "to", None))
        self.menu_File.setTitle(_translate("MainWindow", "&File", None))
        self.menuImport.setTitle(_translate("MainWindow", "Import...", None))
        self.actionHDF5.setText(_translate("MainWindow", "HDF5", None))
        self.actionCSV.setText(_translate("MainWindow", "CSV", None))
        self.actionXML.setText(_translate("MainWindow", "XML", None))
        self.action_Plot.setText(_translate("MainWindow", "&Plot", None))
        self.action_Close.setText(_translate("MainWindow", "&Close", None))

