# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'journal_design.ui'
#
# Created: Thu Feb  9 08:23:36 2017
#      by: PyQt4 UI code generator 4.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1290, 710)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout_2 = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.filterGroupBox = QtGui.QGroupBox(self.centralwidget)
        self.filterGroupBox.setObjectName(_fromUtf8("filterGroupBox"))
        self.gridLayout_3 = QtGui.QGridLayout(self.filterGroupBox)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.titleSyntaxComboBox = QtGui.QComboBox(self.filterGroupBox)
        self.titleSyntaxComboBox.setObjectName(_fromUtf8("titleSyntaxComboBox"))
        self.gridLayout_3.addWidget(self.titleSyntaxComboBox, 1, 2, 1, 1)
        self.userLineEdit = QtGui.QLineEdit(self.filterGroupBox)
        self.userLineEdit.setObjectName(_fromUtf8("userLineEdit"))
        self.gridLayout_3.addWidget(self.userLineEdit, 5, 1, 1, 1)
        self.titleLineEdit = QtGui.QLineEdit(self.filterGroupBox)
        self.titleLineEdit.setObjectName(_fromUtf8("titleLineEdit"))
        self.gridLayout_3.addWidget(self.titleLineEdit, 1, 1, 1, 1)
        self.titleLabel = QtGui.QLabel(self.filterGroupBox)
        self.titleLabel.setObjectName(_fromUtf8("titleLabel"))
        self.gridLayout_3.addWidget(self.titleLabel, 1, 0, 1, 1)
        self.userLabel = QtGui.QLabel(self.filterGroupBox)
        self.userLabel.setObjectName(_fromUtf8("userLabel"))
        self.gridLayout_3.addWidget(self.userLabel, 5, 0, 1, 1)
        self.titleCaseCheckBox = QtGui.QCheckBox(self.filterGroupBox)
        self.titleCaseCheckBox.setObjectName(_fromUtf8("titleCaseCheckBox"))
        self.gridLayout_3.addWidget(self.titleCaseCheckBox, 2, 2, 1, 1)
        self.filterButton = QtGui.QPushButton(self.filterGroupBox)
        self.filterButton.setObjectName(_fromUtf8("filterButton"))
        self.gridLayout_3.addWidget(self.filterButton, 5, 2, 1, 1)
        self.gridLayout_2.addWidget(self.filterGroupBox, 1, 2, 1, 1)
        self.displayGroupBox = QtGui.QGroupBox(self.centralwidget)
        self.displayGroupBox.setObjectName(_fromUtf8("displayGroupBox"))
        self.formLayout = QtGui.QFormLayout(self.displayGroupBox)
        self.formLayout.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.instrumentComboBox = QtGui.QComboBox(self.displayGroupBox)
        self.instrumentComboBox.setObjectName(_fromUtf8("instrumentComboBox"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.instrumentComboBox)
        self.runDatabaseLabel = QtGui.QLabel(self.displayGroupBox)
        self.runDatabaseLabel.setObjectName(_fromUtf8("runDatabaseLabel"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.runDatabaseLabel)
        self.runDatabaseComboBox = QtGui.QComboBox(self.displayGroupBox)
        self.runDatabaseComboBox.setObjectName(_fromUtf8("runDatabaseComboBox"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.runDatabaseComboBox)
        self.instrumentLabel = QtGui.QLabel(self.displayGroupBox)
        self.instrumentLabel.setObjectName(_fromUtf8("instrumentLabel"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.instrumentLabel)
        self.sampleDatabaseLabel = QtGui.QLabel(self.displayGroupBox)
        self.sampleDatabaseLabel.setObjectName(_fromUtf8("sampleDatabaseLabel"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.sampleDatabaseLabel)
        self.sampleDatabaseComboBox = QtGui.QComboBox(self.displayGroupBox)
        self.sampleDatabaseComboBox.setObjectName(_fromUtf8("sampleDatabaseComboBox"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.sampleDatabaseComboBox)
        self.gridLayout_2.addWidget(self.displayGroupBox, 1, 0, 1, 1)
        self.treeView = QtGui.QTreeView(self.centralwidget)
        self.treeView.setObjectName(_fromUtf8("treeView"))
        self.gridLayout_2.addWidget(self.treeView, 2, 0, 1, 3)
        self.databaseGroupBox = QtGui.QGroupBox(self.centralwidget)
        self.databaseGroupBox.setObjectName(_fromUtf8("databaseGroupBox"))
        self.gridLayout = QtGui.QGridLayout(self.databaseGroupBox)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.iptsLineEdit = QtGui.QLineEdit(self.databaseGroupBox)
        self.iptsLineEdit.setObjectName(_fromUtf8("iptsLineEdit"))
        self.gridLayout.addWidget(self.iptsLineEdit, 1, 4, 1, 1)
        self.iptsLabel = QtGui.QLabel(self.databaseGroupBox)
        self.iptsLabel.setObjectName(_fromUtf8("iptsLabel"))
        self.gridLayout.addWidget(self.iptsLabel, 1, 3, 1, 1)
        self.dateRangeLabel = QtGui.QLabel(self.databaseGroupBox)
        self.dateRangeLabel.setObjectName(_fromUtf8("dateRangeLabel"))
        self.gridLayout.addWidget(self.dateRangeLabel, 0, 3, 1, 1)
        self.scanLineEdit = QtGui.QLineEdit(self.databaseGroupBox)
        self.scanLineEdit.setObjectName(_fromUtf8("scanLineEdit"))
        self.gridLayout.addWidget(self.scanLineEdit, 2, 4, 1, 1)
        self.dateEnd = QtGui.QDateEdit(self.databaseGroupBox)
        self.dateEnd.setCalendarPopup(True)
        self.dateEnd.setObjectName(_fromUtf8("dateEnd"))
        self.gridLayout.addWidget(self.dateEnd, 0, 6, 1, 1)
        self.scanLabel = QtGui.QLabel(self.databaseGroupBox)
        self.scanLabel.setObjectName(_fromUtf8("scanLabel"))
        self.gridLayout.addWidget(self.scanLabel, 2, 3, 1, 1)
        self.dateToLabel = QtGui.QLabel(self.databaseGroupBox)
        self.dateToLabel.setTextFormat(QtCore.Qt.LogText)
        self.dateToLabel.setObjectName(_fromUtf8("dateToLabel"))
        self.gridLayout.addWidget(self.dateToLabel, 0, 5, 1, 1)
        self.dateStart = QtGui.QDateEdit(self.databaseGroupBox)
        self.dateStart.setCalendarPopup(True)
        self.dateStart.setObjectName(_fromUtf8("dateStart"))
        self.gridLayout.addWidget(self.dateStart, 0, 4, 1, 1)
        self.databaseButton = QtGui.QPushButton(self.databaseGroupBox)
        self.databaseButton.setObjectName(_fromUtf8("databaseButton"))
        self.gridLayout.addWidget(self.databaseButton, 2, 6, 1, 1)
        self.gridLayout_2.addWidget(self.databaseGroupBox, 1, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1290, 20))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menu_File = QtGui.QMenu(self.menubar)
        self.menu_File.setObjectName(_fromUtf8("menu_File"))
        self.menuImport = QtGui.QMenu(self.menu_File)
        self.menuImport.setObjectName(_fromUtf8("menuImport"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.actionHDF5 = QtGui.QAction(MainWindow)
        self.actionHDF5.setObjectName(_fromUtf8("actionHDF5"))
        self.actionCSV = QtGui.QAction(MainWindow)
        self.actionCSV.setObjectName(_fromUtf8("actionCSV"))
        self.actionXML = QtGui.QAction(MainWindow)
        self.actionXML.setObjectName(_fromUtf8("actionXML"))
        self.action_Plot = QtGui.QAction(MainWindow)
        self.action_Plot.setObjectName(_fromUtf8("action_Plot"))
        self.action_Close = QtGui.QAction(MainWindow)
        self.action_Close.setObjectName(_fromUtf8("action_Close"))
        self.menuImport.addAction(self.actionHDF5)
        self.menuImport.addAction(self.actionCSV)
        self.menuImport.addAction(self.actionXML)
        self.menu_File.addAction(self.menuImport.menuAction())
        self.menu_File.addAction(self.action_Plot)
        self.menu_File.addSeparator()
        self.menu_File.addAction(self.action_Close)
        self.menubar.addAction(self.menu_File.menuAction())
        self.titleLabel.setBuddy(self.titleLineEdit)
        self.userLabel.setBuddy(self.userLineEdit)
        self.instrumentLabel.setBuddy(self.instrumentComboBox)
        self.iptsLabel.setBuddy(self.iptsLineEdit)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "JournalView", None))
        self.filterGroupBox.setTitle(_translate("MainWindow", "Table Filters", None))
        self.titleLabel.setText(_translate("MainWindow", "Title:", None))
        self.userLabel.setText(_translate("MainWindow", "User:", None))
        self.titleCaseCheckBox.setText(_translate("MainWindow", "Case Sensitive", None))
        self.filterButton.setText(_translate("MainWindow", "Apply Filter", None))
        self.displayGroupBox.setTitle(_translate("MainWindow", "Database", None))
        self.runDatabaseLabel.setText(_translate("MainWindow", "Run Data", None))
        self.instrumentLabel.setText(_translate("MainWindow", "Instrument:", None))
        self.sampleDatabaseLabel.setText(_translate("MainWindow", "Sample Data", None))
        self.databaseGroupBox.setTitle(_translate("MainWindow", "Database/Table Filters", None))
        self.iptsLabel.setText(_translate("MainWindow", "IPTS:", None))
        self.dateRangeLabel.setText(_translate("MainWindow", "Date Range:", None))
        self.scanLabel.setText(_translate("MainWindow", "Scan ID list (ex: 1001 1005-1009 ...):", None))
        self.dateToLabel.setText(_translate("MainWindow", "to", None))
        self.databaseButton.setText(_translate("MainWindow", "Update Table", None))
        self.menu_File.setTitle(_translate("MainWindow", "&File", None))
        self.menuImport.setTitle(_translate("MainWindow", "Import...", None))
        self.actionHDF5.setText(_translate("MainWindow", "HDF5", None))
        self.actionCSV.setText(_translate("MainWindow", "CSV", None))
        self.actionXML.setText(_translate("MainWindow", "XML", None))
        self.action_Plot.setText(_translate("MainWindow", "&Plot", None))
        self.action_Close.setText(_translate("MainWindow", "&Close", None))

